from aoc2024 import day08
import pytest

@pytest.fixture
def sample_input():
    return """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""


def test_day08_part1(sample_input):
    assert day08.part1(sample_input) == 14

def test_day08_part2(sample_input):
    assert day08.part2(sample_input) == 34